#!/bin/sh
xrandr --output DP-2-1 --off --output DP-2-2 --off --output DP-2-3 --off --output eDP-1 --mode 1360x768 --pos 0x282 --rotate normal --output HDMI-2 --mode 1680x1050 --pos 1360x0 --rotate normal --output HDMI-1 --mode 1280x1024 --pos 3040x26 --rotate normal --output DP-2 --off --output DP-1 --off
