#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import os
import SimpleHTTPServer
import SocketServer

def parse_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--port',
        '-p',
        default='8080',
        action='store'
    )
    parser.add_argument(
        '--dir',
        '-d',
        default='',
        action='store',
        help='reltive path to share'
    )
    arguments = parser.parse_args()
    return arguments

def main(args):
    share = os.path.join(os.getcwd(), args.dir)
    os.chdir(share)

    port = int(args.port)
    handler = SimpleHTTPServer.SimpleHTTPRequestHandler
    httpd = SocketServer.TCPServer(("", port), handler)

    print "serving at port", port
    httpd.serve_forever()

if __name__ == '__main__':
    args = parse_arguments()
    main(args)

