#!/bin/bash

## based on termdown https://github.com/trehn/termdown

project=$1
task=$2

day=$(date +"%m-%d-%Y")
horizontal_line="-------------------------------------------------------------" 

touch ~/Dropbox/timetracker/$day.txt
cp ~/Dropbox/timetracker/$day.txt /tmp/timetracker_$day

termdown 2> /tmp/timetracker_timer
working_hours=`cat /tmp/timetracker_timer | cut -f2`
echo "$working_hours | $project - $task" >> /tmp/timetracker_$day

column -t -s "|" /tmp/timetracker_$day > ~/Dropbox/timetracker/$day.txt

echo -e "--- Todays TimeTracker ---\n"
while read line; 
do 
		echo -e "$line \n$horizontal_line"
done < ~/Dropbox/timetracker/$day.txt
